/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class CustomerSupport extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public CustomerSupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requests = new javax.swing.JLabel();
        calls = new javax.swing.JLabel();
        customersList = new javax.swing.JLabel();
        technicalProfessionalsList = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requests.setText(" ");
        requests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestsMouseClicked(evt);
            }
        });
        getContentPane().add(requests, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 90, 20));

        calls.setText(" ");
        calls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                callsMouseClicked(evt);
            }
        });
        getContentPane().add(calls, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 50, 20));

        customersList.setText(" ");
        customersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersListMouseClicked(evt);
            }
        });
        getContentPane().add(customersList, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 150, 20));

        technicalProfessionalsList.setText(" ");
        technicalProfessionalsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                technicalProfessionalsListMouseClicked(evt);
            }
        });
        getContentPane().add(technicalProfessionalsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 250, 20));

        logout.setText(" ");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 120, 30));

        page.setIcon(new javax.swing.ImageIcon("C:\\Users\\giann\\Documents\\Εργασίες\\ProFound\\Mockups\\Customer Support.png")); // NOI18N
        page.setText(" ");
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void requestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsMouseClicked
        Player_MyCalendar a = new Player_MyCalendar();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_requestsMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Home a = new Home();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void callsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callsMouseClicked
        Player_Stats a = new Player_Stats();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_callsMouseClicked

    private void customersListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersListMouseClicked
        Player_Feedback a = new Player_Feedback();
        a.setVisible(true);
        this.dispose();    }//GEN-LAST:event_customersListMouseClicked

    private void technicalProfessionalsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_technicalProfessionalsListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_technicalProfessionalsListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calls;
    private javax.swing.JLabel customersList;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel page;
    private javax.swing.JLabel requests;
    private javax.swing.JLabel technicalProfessionalsList;
    // End of variables declaration//GEN-END:variables
}
