/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requests = new javax.swing.JLabel();
        reviews = new javax.swing.JLabel();
        myProfile = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        searchTechnicalProfessionals = new javax.swing.JLabel();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requests.setText(" ");
        requests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestsMouseClicked(evt);
            }
        });
        getContentPane().add(requests, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 254, 80, 20));

        reviews.setText(" ");
        reviews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewsMouseClicked(evt);
            }
        });
        getContentPane().add(reviews, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 376, 80, -1));

        myProfile.setText(" ");
        myProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myProfileMouseClicked(evt);
            }
        });
        getContentPane().add(myProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 100, 10));

        logout.setText(" ");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 20, 110, 30));

        searchTechnicalProfessionals.setText(" ");
        searchTechnicalProfessionals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTechnicalProfessionalsMouseClicked(evt);
            }
        });
        getContentPane().add(searchTechnicalProfessionals, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 280, 10));

        page.setIcon(new javax.swing.ImageIcon("C:\\Users\\giann\\Documents\\Εργασίες\\ProFound\\Mockups\\Customer.png")); // NOI18N
        page.setText(" ");
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void requestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsMouseClicked
       CustomerRequests a =  new CustomerRequests();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_requestsMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Home a = new Home();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void reviewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewsMouseClicked
        CustomerReview a = new CustomerReview();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reviewsMouseClicked

    private void searchTechnicalProfessionalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTechnicalProfessionalsMouseClicked
       CustomerTechnicalProfessionalSearch a =  new CustomerTechnicalProfessionalSearch();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_searchTechnicalProfessionalsMouseClicked

    private void myProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myProfileMouseClicked
        CustomerMyProfile a = new CustomerMyProfile();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logout;
    private javax.swing.JLabel myProfile;
    private javax.swing.JLabel page;
    private javax.swing.JLabel requests;
    private javax.swing.JLabel reviews;
    private javax.swing.JLabel searchTechnicalProfessionals;
    // End of variables declaration//GEN-END:variables
}
