/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class SystemAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public SystemAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        technicalProfessionals = new javax.swing.JLabel();
        customerSupport = new javax.swing.JLabel();
        customers = new javax.swing.JLabel();
        reviews = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        technicalProfessionals.setText(" ");
        technicalProfessionals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                technicalProfessionalsMouseClicked(evt);
            }
        });
        getContentPane().add(technicalProfessionals, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 220, 20));

        customerSupport.setText(" ");
        customerSupport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerSupportMouseClicked(evt);
            }
        });
        getContentPane().add(customerSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 170, 20));

        customers.setText(" ");
        getContentPane().add(customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 100, 20));

        reviews.setText(" ");
        getContentPane().add(reviews, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 80, 30));

        logout.setText(" ");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 20, 110, 30));

        page.setIcon(new javax.swing.ImageIcon("C:\\Users\\giann\\Documents\\Εργασίες\\ProFound\\Mockups\\System Admin.png")); // NOI18N
        page.setText(" ");
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void technicalProfessionalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_technicalProfessionalsMouseClicked
        Physiotherapist_StengthEx a = new Physiotherapist_StengthEx();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_technicalProfessionalsMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Home a = new Home();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void customerSupportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerSupportMouseClicked
        Physiotherapist_InjuryEx a = new Physiotherapist_InjuryEx();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerSupportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerSupport;
    private javax.swing.JLabel customers;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel page;
    private javax.swing.JLabel reviews;
    private javax.swing.JLabel technicalProfessionals;
    // End of variables declaration//GEN-END:variables
}
